export interface PhilosophicalQuote {
  content: string;
  author: string;
}

export const PHILOSOPHICAL_QUOTES: PhilosophicalQuote[] = [
  { content: "O homem está condenado a ser livre; porque, uma vez lançado ao mundo, ele é responsável por tudo o que faz.", author: "Jean-Paul Sartre" },
  { content: "Não importa o que fizeram de nós, o que importa é o que nós fazemos com o que fizeram de nós.", author: "Jean-Paul Sartre" },
  { content: "O inferno são os outros.", author: "Jean-Paul Sartre" },
  { content: "O segredo da existência humana não está apenas em viver, mas em encontrar algo para o qual viver.", author: "Fiódor Dostoiévski" },
  { content: "A dor e o sofrimento são sempre inevitáveis para uma inteligência generosa e um coração profundo.", author: "Fiódor Dostoiévski" },
  { content: "A maior felicidade é saber a fonte da infelicidade.", author: "Fiódor Dostoiévski" },
  { content: "Aquele que tem um porquê para viver pode suportar quase qualquer como.", author: "Friedrich Nietzsche" },
  { content: "O que não me mata me torna mais forte.", author: "Friedrich Nietzsche" },
  { content: "É preciso ter o caos dentro de si para dar à luz uma estrela cintilante.", author: "Friedrich Nietzsche" },
  { content: "Aquele que olha para fora sonha; aquele que olha para dentro desperta.", author: "Carl Jung" },
  { content: "Até que você torne o inconsciente consciente, ele direcionará sua vida e você o chamará de destino.", author: "Carl Jung" },
  { content: "Eu não sou o que aconteceu comigo, eu sou o que escolhi me tornar.", author: "Carl Jung" },
  { content: "Um dia, em retrospecto, os anos de luta parecerão os mais belos.", author: "Sigmund Freud" },
  { content: "A nossa capacidade de amar é o que nos torna vulneráveis à dor.", author: "Sigmund Freud" },
  { content: "Olhar para trás é como ver a própria sombra: não nos ajuda a caminhar, mas nos lembra de onde viemos.", author: "Sigmund Freud" },
  { content: "No meio do inverno, aprendi finalmente que havia em mim um verão invencível.", author: "Albert Camus" },
  { content: "A única maneira de lidar com um mundo sem liberdade é tornar-se tão absolutamente livre que sua própria existência seja um ato de rebeldia.", author: "Albert Camus" },
  { content: "Seja feliz, mesmo que isso pareça um absurdo.", author: "Albert Camus" },
  { content: "O homem é livre para fazer o que quer, mas não livre para querer o que quer.", author: "Arthur Schopenhauer" },
  { content: "Toda a verdade passa por três estágios. Primeiro, é ridicularizada. Segundo, é violentamente contestada. Terceiro, é aceita como óbvia.", author: "Arthur Schopenhauer" },
  { content: "A solidão é a sorte de todos os espíritos excepcionais.", author: "Arthur Schopenhauer" },
  { content: "A vida só pode ser compreendida olhando-se para trás; mas só pode ser vivida olhando-se para a frente.", author: "Søren Kierkegaard" },
  { content: "A ansiedade é o vertigem da liberdade.", author: "Søren Kierkegaard" },
  { content: "Ousar é perder o equilíbrio momentaneamente. Não ousar é perder-se.", author: "Søren Kierkegaard" },
  { content: "Sem a faculdade de esquecer, o nosso passado pesaria tanto sobre o nosso presente que não teríamos forças para dar um passo.", author: "Emil Cioran" },
  { content: "A consciência é muito mais do que a espinha dorsal da alma; é a sua ferida.", author: "Emil Cioran" },
  { content: "A felicidade da sua vida depende da qualidade dos seus pensamentos.", author: "Marcus Aurelius" },
  { content: "Você tem poder sobre sua mente — não sobre eventos externos. Perceba isso e você encontrará força.", author: "Marcus Aurelius" },
  { content: "A melhor vingança é ser diferente daquele que causou o dano.", author: "Marcus Aurelius" },
  { content: "Nenhum vento sopra a favor daquele que não sabe para onde ir.", author: "Seneca" },
  { content: "Sofremos mais frequentemente na imaginação do que na realidade.", author: "Seneca" },
  { content: "Apressa-te a viver bem e pensa que cada dia é, por si só, uma vida.", author: "Seneca" },
  { content: "Não são as coisas que nos perturbam, mas as opiniões que temos sobre elas.", author: "Epictetus" },
  { content: "Se você deseja melhorar, contente-se em ser considerado tolo e estúpido.", author: "Epictetus" },
  { content: "Não rir, não chorar, não indignar-se, mas compreender.", author: "Baruch Spinoza" },
  { content: "A paz não é a ausência de guerra, é uma virtude, um estado de espírito, uma disposição para a benevolência, confiança e justiça.", author: "Baruch Spinoza" },
  { content: "Duas coisas enchem o ânimo de admiração: o céu estrelado acima de mim e a lei moral em mim.", author: "Immanuel Kant" },
  { content: "Avalia-se a inteligência de um indivíduo pela quantidade de incertezas que ele é capaz de suportar.", author: "Immanuel Kant" },
  { content: "O coração tem razões que a própria razão desconhece.", author: "Blaise Pascal" },
  { content: "Toda a infelicidade dos homens provém de uma única coisa, que é não saberem permanecer em repouso num quarto.", author: "Blaise Pascal" },
  { content: "Uma vida não examinada não vale a pena ser vivida.", author: "Sócrates" },
  { content: "Só sei que nada sei.", author: "Sócrates" },
  { content: "Conhece-te a ti mesmo e conhecerás o universo e os deuses.", author: "Sócrates" },
  { content: "A coisa mais importante não é viver, mas viver bem.", author: "Platão" },
  { content: "Somos o que fazemos repetidamente. A excelência, portanto, não é um ato, mas um hábito.", author: "Aristóteles" },
  { content: "Conhecer a si mesmo é o começo de toda sabedoria.", author: "Aristóteles" },
  { content: "Ninguém entra em um mesmo rio duas vezes, pois o rio não é o mesmo e o homem não é o mesmo.", author: "Heráclito" },
  { content: "Penso, logo existo.", author: "René Descartes" },
  { content: "A medida do viver não está na duração, mas no uso que se faz dele.", author: "Michel de Montaigne" },
  { content: "Quando não somos mais capazes de mudar uma situação, somos desafiados a mudar a nós mesmos.", author: "Viktor Frankl" },
  { content: "Tudo pode ser tirado de um homem, exceto uma coisa: a última das liberdades humanas — escolher sua atitude em qualquer circunstância.", author: "Viktor Frankl" },
  { content: "A maior descoberta da minha geração é que o ser humano pode alterar sua vida mudando sua atitude mental.", author: "William James" },
  { content: "A criatividade requer coragem para se desprender das certezas.", author: "Erich Fromm" },
  { content: "O amor não é um sentimento à toa, mas uma arte que requer conhecimento e esforço.", author: "Erich Fromm" },
  { content: "A depressão é a incapacidade de construir um futuro.", author: "Rollo May" },
  { content: "A única mentira perigosa é aquela que você conta a si mesmo.", author: "Alfred Adler" },
  { content: "O curioso paradoxo é que quando eu me aceito como sou, então eu posso mudar.", author: "Carl Rogers" }
];
