name: Simulador de Deploy e Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Instalar Dependências
        run: npm ci
        
      - name: Rodar Vite Build (Verifica Erros Ocultos de Compilação)
        run: npm run build
