name: Deploy Regras de Seguranca Firestore

on:
  push:
    branches:
      - main
    paths:
      - 'firestore.rules'
  pull_request:
    branches:
      - main
    paths:
      - 'firestore.rules'

permissions:
  contents: read
  id-token: write

jobs:
  deploy_rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Autenticar no Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy Firestore Rules
        run: firebase deploy --only firestore:rules --project gassistant-83242


