name: Deploy Regras de Seguranca Firestore

on:
  push:
    branches: [ "main" ]
    paths:
      - 'firestore.rules'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy_rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy ao Firebase Database
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore:rules --project gassistant-83242
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          PROJECT_ID: gassistant-83242


