name: Validacao de Tipagem e Sintaxe (Lint)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Instalar Dependências
        run: npm ci
      - name: Checar Tipagem TypeScript
        run: npx tsc --noEmit
      - name: Checar Lint (ESLint)
        run: npm run lint
