name: Test Check

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '.env.example'
      - 'ACCESS_POLICY.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '.env.example'
      - 'ACCESS_POLICY.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm test
